### ISSUE TITLE
Add buttons and/or rotary encoder

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/rgb-led#2]
They can be used to step through different effects.

**Comment by dbrgn** [comment]
They can be used to step through different effects.

**Comment by dbrgn** [comment]
I think the best solution would be to add a single rotary encoder.

**Comment by dns2utf8** [comment]
I would prefere a rotay encoder and two buttons.

**Comment by dbrgn** [comment]
The other option is an ESP8266 and an app :)

**Comment by dbrgn** [comment]
Something like this? http://mikroshop.ch/?gruppe=10&artikel=44 Has an integrated push-button.
