### ISSUE TITLE
Mounting holes

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/rgb-led#3]

**Comment by schmijos** [comment]
?

**Comment by dbrgn** [comment]
Das PCB (v2.1) braucht noch mounting holes :) So wie hier, einfach professioneller:

![img](https://pbs.twimg.com/media/B-jyNfNIMAAuuTR.jpg)

**Comment by schmijos** [comment]
Achso :-)

**Comment by rnestler** [comment]
Wie geil :smile:

**Comment by rnestler** [comment]
closed with #11
